apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: reactor

spec:
  version: "v!!!VERSION!!!"
  homepage: https://github.com/zimagi/reactor
  shortDescription: "Kubectl plugin for managing development Kubernetes clusters"
  description: |
    Facilitates the creation and initialization, the runtime management, and the
    destruction and cleaning of local Minikube Kubernetes clusters.  This cluster uses
    Terraform provisioned and ArgoCD managed cluster service projects to create complete
    ready to use develop clusters that try to mimic production environment as much
    as possible.

  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux

    uri: "https://github.com/zimagi/reactor/releases/download/!!!VERSION!!!/reactor.tar.gz"
    sha256: "!!!SHA256!!!"

    bin: "./kubectl-reactor"
    files:
    - from: "scripts/*reactor*"
      to: "."

    - from: "scripts/state/*.sh"
      to: "state"
    - from: "scripts/commands/*.sh"
      to: "commands"
    - from: "scripts/utilities/*.sh"
      to: "utilities"

    - from: "LICENSE"
      to: "."
    - from: "VERSION"
      to: "."
    - from: "*.*"
      to: "."
