#!/usr/bin/env bash
#
# Usage:
#
#  $> source start [--env] project_name [environment:local]
#
#=========================================================================================
# Environment
#
export __script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "$PATH" != *"${__script_dir}/bin:"* ]]; then
  export PATH="${__script_dir}/bin:${PATH}"
fi

env_only=0
args=()

for arg in "$@"; do
  if [ "$arg" == "--env" ]; then
    env_only=1
  else
    args=("${args[@]}" "$arg")
  fi
done

if [ ! "${args[0]:-}" ]; then
  echo """
 Usage: source start [--env] project_name [environment:local]
"""
  return
fi

export REACTOR_PROJECT_NAME="${args[0]:-}"
export REACTOR_ENVIRONMENT="${args[1]:-local}"

if [ $env_only -eq 1 ]; then
  return
fi
#
#=========================================================================================
# Execution
#
reactor up
