version: 2

ubuntu_amd64: &ubuntu_amd64
    resource_class: medium
    machine:
        image: ubuntu-2404:current

ubuntu_arm64: &ubuntu_arm64
    resource_class: arm.medium
    machine:
        image: ubuntu-2404:current

check_shell_paths: &check_shell_paths
    name: Test shell paths
    command: which bash && which zsh && which sh

install_apt_zsh: &install_apt_zsh
    name: Install ZSh
    command: sudo apt install zsh

bootstrap: &bootstrap
    name: Bootstrap test OS
    command: ./tests/bootstrap.sh

session: &session
    name: Test Docker image
    command: ./tests/run_session.sh

session_env: &session_env
    REACTOR_PARENT_IMAGE: ubuntu:22.04
    MINIKUBE_CPUS: 2
    MINIKUBE_MEMORY: 4096

dump_log: &dump_log
    name: Dump reactor command log
    when: always
    command: cat ./tests/project/logs/reactor.log

test_bash: &test_bash
    steps:
        - checkout
        - run:
            <<: *bootstrap
            shell: /usr/bin/bash
            environment: *session_env
        - run:
            <<: *session
            shell: /usr/bin/bash
            environment: *session_env
        - run: *dump_log

test_ubuntu_zsh: &test_ubuntu_zsh
    steps:
        - checkout
        - run: *install_apt_zsh
        - run:
            <<: *bootstrap
            shell: /usr/bin/zsh
            environment: *session_env
        - run:
            <<: *session
            shell: /usr/bin/zsh
            environment: *session_env
        - run: *dump_log

test_sh: &test_sh
    steps:
        - checkout
        - run:
            <<: *bootstrap
            shell: /usr/bin/sh
            environment: *session_env
        - run:
            <<: *session
            shell: /usr/bin/sh
            environment: *session_env
        - run: *dump_log

jobs:
    test-amd64-ubuntu-bash:
        <<: [*ubuntu_amd64, *test_bash]

    test-amd64-ubuntu-zsh:
        <<: [*ubuntu_amd64, *test_ubuntu_zsh]

    test-amd64-ubuntu-sh:
        <<: [*ubuntu_amd64, *test_sh]

    test-arm64-ubuntu-bash:
        <<: [*ubuntu_arm64, *test_bash]

    test-arm64-ubuntu-zsh:
        <<: [*ubuntu_arm64, *test_ubuntu_zsh]

    test-arm64-ubuntu-sh:
        <<: [*ubuntu_arm64, *test_sh]

    deploy-docker-amd64-latest:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy latest AMD Docker image
                command: ./docker/deploy_image.sh standard latest
                environment:
                    REACTOR_PARENT_IMAGE: ubuntu:22.04

    deploy-docker-arm64-latest:
        <<: *ubuntu_arm64
        steps:
            - checkout
            - run:
                name: Deploy latest ARM Docker image
                command: ./docker/deploy_image.sh standard latest
                environment:
                    REACTOR_PARENT_IMAGE: ubuntu:22.04

    deploy-docker-latest:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy latest Docker platform manifest
                command: ./docker/deploy_manifest.sh standard latest

    deploy-docker-nvidia-amd64-latest:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy latest AMD Nvidia Docker image
                command: ./docker/deploy_image.sh nvidia latest
                environment:
                    REACTOR_PARENT_IMAGE: nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04

    deploy-docker-nvidia-latest:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy latest Nvidia Docker platform manifest
                command: ./docker/deploy_manifest.sh nvidia latest

    deploy-docker-amd64-version:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy versioned AMD Docker image
                command: ./docker/deploy_image.sh
                environment:
                    REACTOR_PARENT_IMAGE: ubuntu:22.04

    deploy-docker-arm64-version:
        <<: *ubuntu_arm64
        steps:
            - checkout
            - run:
                name: Deploy versioned ARM Docker image
                command: ./docker/deploy_image.sh
                environment:
                    REACTOR_PARENT_IMAGE: ubuntu:22.04

    deploy-docker-version:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy versioned Docker platform manifest
                command: ./docker/deploy_manifest.sh

    deploy-docker-nvidia-amd64-version:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy versioned AMD Nvidia Docker image
                command: ./docker/deploy_image.sh nvidia
                environment:
                    REACTOR_PARENT_IMAGE: nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04

    deploy-docker-nvidia-version:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy versioned Nvidia Docker platform manifest
                command: ./docker/deploy_manifest.sh nvidia

workflows:
    version: 2
    deploy:
        jobs:
            - test-amd64-ubuntu-bash:
                filters:
                    tags:
                        only: /.*/

            - test-amd64-ubuntu-zsh:
                filters:
                    tags:
                        only: /.*/

            - test-amd64-ubuntu-sh:
                filters:
                    tags:
                        only: /.*/

            - test-arm64-ubuntu-bash:
                filters:
                    tags:
                        only: /.*/

            - test-arm64-ubuntu-zsh:
                filters:
                    tags:
                        only: /.*/

            - test-arm64-ubuntu-sh:
                filters:
                    tags:
                        only: /.*/

            - deploy-docker-amd64-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - test-amd64-ubuntu-bash
                    - test-amd64-ubuntu-zsh
                    - test-amd64-ubuntu-sh

            - deploy-docker-arm64-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - test-arm64-ubuntu-bash
                    - test-arm64-ubuntu-zsh
                    - test-arm64-ubuntu-sh

            - deploy-docker-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - deploy-docker-amd64-latest
                    - deploy-docker-arm64-latest

            - deploy-docker-nvidia-amd64-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - test-amd64-ubuntu-bash
                    - test-amd64-ubuntu-zsh
                    - test-amd64-ubuntu-sh

            - deploy-docker-nvidia-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - deploy-docker-nvidia-amd64-latest

            - deploy-docker-amd64-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - test-amd64-ubuntu-bash
                    - test-amd64-ubuntu-zsh
                    - test-amd64-ubuntu-sh

            - deploy-docker-arm64-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - test-arm64-ubuntu-bash
                    - test-arm64-ubuntu-zsh
                    - test-arm64-ubuntu-sh

            - deploy-docker-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docker-amd64-version
                    - deploy-docker-arm64-version

            - deploy-docker-nvidia-amd64-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - test-amd64-ubuntu-bash
                    - test-amd64-ubuntu-zsh
                    - test-amd64-ubuntu-sh

            - deploy-docker-nvidia-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docker-nvidia-amd64-version
