version: 2

ubuntu_amd64: &ubuntu_amd64
    resource_class: medium
    machine:
        image: ubuntu-2404:current

ubuntu_arm64: &ubuntu_arm64
    resource_class: arm.medium
    machine:
        image: ubuntu-2404:current

bootstrap: &bootstrap
    name: Bootstrap test OS
    command: ./tests/bootstrap.sh

session: &session
    name: Test Docker image
    command: ./tests/run_session.sh

session_env: &session_env
    REACTOR_PARENT_IMAGE: ubuntu:22.04
    MINIKUBE_CPUS: 2
    MINIKUBE_MEMORY: 4096

dump_log: &dump_log
    name: Dump reactor command log
    when: always
    command: test ! -f ./tests/project/logs/reactor.log || cat ./tests/project/logs/reactor.log

test_bash: &test_bash
    steps:
        - checkout
        - run:
            <<: *bootstrap
            shell: /usr/bin/bash
            environment: *session_env
        - run:
            <<: *session
            shell: /usr/bin/bash
            environment: *session_env
        - run: *dump_log

jobs:
    test-amd64-ubuntu-bash:
        <<: [*ubuntu_amd64, *test_bash]

    test-arm64-ubuntu-bash:
        <<: [*ubuntu_arm64, *test_bash]

    deploy-docs:
        docker:
            - image: python:3.10
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "SHA256:Et02GjIRCFTsh5JKh7j9STKDqFmdx3S2RYTiTNooa+Q"
            - run:
                name: Install core dependencies
                command: |
                    apt-get update
                    apt-get install -y git g++ gcc make

            - checkout
            - run:
                name: Install documentation dependencies
                command: pip install --no-cache-dir -r ./docs/requirements.txt

            - run:
                name: Deploy documentation
                command: |
                    git config --global user.name "CircleCI ( ${CIRCLE_USERNAME} )"
                    git config --global user.email "${CIRCLE_USERNAME}@${CIRCLE_BRANCH}"
                    ./docs/deploy.sh git@github.com:zimagi/reactor.git "${CIRCLE_BRANCH}"

    deploy-release:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - checkout
            - run:
                name: Deploy release
                command: |
                    mkdir /tmp/reactor
                    cp -R ./scripts /tmp/reactor/scripts
                    cp ./requirements.txt /tmp/reactor/requirements.txt
                    cp ./VERSION /tmp/reactor/VERSION
                    cp ./LICENSE /tmp/reactor/LICENSE

                    mkdir /tmp/release
                    tar -czf /tmp/release/reactor.tar.gz -C /tmp/reactor /tmp/reactor
                    cp ./reactor.template.yaml /tmp/release/reactor.yaml

                    VERSION="$(cat ./VERSION)"
                    SHA256="$(sha256sum /tmp/release/reactor.tar.gz | sed 's/\s.*$//')"

                    sed -i "s/!!!VERSION!!!/${VERSION}/" /tmp/release/reactor.yaml
                    sed -i "s/!!!SHA256!!!/${SHA256}/" /tmp/release/reactor.yaml

                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/release/

    deploy-docker-amd64-latest:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy latest AMD Docker image
                command: ./docker/deploy_image.sh standard latest
                environment:
                    REACTOR_PARENT_IMAGE: ubuntu:22.04

    deploy-docker-arm64-latest:
        <<: *ubuntu_arm64
        steps:
            - checkout
            - run:
                name: Deploy latest ARM Docker image
                command: ./docker/deploy_image.sh standard latest
                environment:
                    REACTOR_PARENT_IMAGE: ubuntu:22.04

    deploy-docker-latest:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy latest Docker platform manifest
                command: ./docker/deploy_manifest.sh standard latest

    deploy-docker-nvidia-amd64-latest:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy latest AMD Nvidia Docker image
                command: ./docker/deploy_image.sh nvidia latest
                environment:
                    REACTOR_PARENT_IMAGE: nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04

    deploy-docker-nvidia-latest:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy latest Nvidia Docker platform manifest
                command: ./docker/deploy_manifest.sh nvidia latest

    deploy-docker-amd64-version:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy versioned AMD Docker image
                command: ./docker/deploy_image.sh
                environment:
                    REACTOR_PARENT_IMAGE: ubuntu:22.04

    deploy-docker-arm64-version:
        <<: *ubuntu_arm64
        steps:
            - checkout
            - run:
                name: Deploy versioned ARM Docker image
                command: ./docker/deploy_image.sh
                environment:
                    REACTOR_PARENT_IMAGE: ubuntu:22.04

    deploy-docker-version:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy versioned Docker platform manifest
                command: ./docker/deploy_manifest.sh

    deploy-docker-nvidia-amd64-version:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy versioned AMD Nvidia Docker image
                command: ./docker/deploy_image.sh nvidia
                environment:
                    REACTOR_PARENT_IMAGE: nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04

    deploy-docker-nvidia-version:
        <<: *ubuntu_amd64
        steps:
            - checkout
            - run:
                name: Deploy versioned Nvidia Docker platform manifest
                command: ./docker/deploy_manifest.sh nvidia

workflows:
    version: 2
    deploy:
        jobs:
            - test-amd64-ubuntu-bash:
                filters:
                    tags:
                        only: /.*/

            - test-arm64-ubuntu-bash:
                filters:
                    tags:
                        only: /.*/

            - deploy-docs:
                filters:
                    branches:
                        only:
                            - main
                            - docs
                requires:
                    - test-amd64-ubuntu-bash
                    - test-arm64-ubuntu-bash

            - deploy-release:
                filters:
                    branches:
                        only:
                            - main

            - deploy-docker-amd64-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - deploy-docs

            - deploy-docker-arm64-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - deploy-docs

            - deploy-docker-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - deploy-docker-amd64-latest
                    - deploy-docker-arm64-latest

            - deploy-docker-nvidia-amd64-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - deploy-docs

            - deploy-docker-nvidia-latest:
                filters:
                    tags:
                        ignore: /.*/
                    branches:
                        only: main
                requires:
                    - deploy-docker-nvidia-amd64-latest

            - deploy-docker-amd64-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docs

            - deploy-docker-arm64-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docs

            - deploy-docker-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docker-amd64-version
                    - deploy-docker-arm64-version

            - deploy-docker-nvidia-amd64-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docs

            - deploy-docker-nvidia-version:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - deploy-docker-nvidia-amd64-version
